name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy    # or 'deploy' if you're using that branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: cd profile-v/ && npm install

      - name: Build site
        run: cd profile-v/ && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./profile-v/dist
